# Generated by Django 4.1.5 on 2023-02-27 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUpload',
            new_name='FilesUploaded',
        ),
    ]
