# Generated by Django 4.2.1 on 2023-05-23 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pmp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pmp', '0003_remove_filesuploaded_document_generic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=pmp.models.upload_to)),
                ('status', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
